# Generated by Django 4.0.4 on 2022-05-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='submitted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='featured_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
